import type { Metadata } from 'next';
import {
  pretendardRegular,
  pretendardSemiBold,
  pretendardBold,
} from '@/styles/fonts';
import './globals.css';
import ClientProviders from '@/components/clientProviders';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${pretendardRegular.variable} ${pretendardSemiBold.variable} ${pretendardBold.variable}`}
      >
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
